name = "QuasiMonteCarlo"
uuid = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
authors = ["ludoro <ludovicobessi@gmail.com>, Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.3.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LatticeRules = "73f95e8e-ec14-4e6a-8b18-0d2e271c4e55"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extensions]
QuasiMonteCarloDistributionsExt = "Distributions"

[compat]
Accessors = "0.1"
Aqua = "0.8"
Combinatorics = "1"
ConcreteStructs = "0.2"
Distributions = "0.25"
HypothesisTests = "0.10.4, 0.11"
IntervalArithmetic = "0.21"
LatticeRules = "0.0.1"
LinearAlgebra = "1.10"
Primes = "0.5"
Random = "1.10"
Sobol = "1.5"
Statistics = "1"
StatsBase = "0.33, 0.34"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Combinatorics", "Distributions", "HypothesisTests", "IntervalArithmetic", "LinearAlgebra", "Primes", "Random", "Statistics", "StatsBase", "Test"]