name = "QuasiMonteCarlo"
uuid = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
authors = ["ludoro <ludovicobessi@gmail.com>, Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.2.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LatticeRules = "73f95e8e-ec14-4e6a-8b18-0d2e271c4e55"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"

[compat]
Distributions = "0.21, 0.22, 0.23, 0.24"
LatinHypercubeSampling = "1.2"
LatticeRules = "0.0.1"
Sobol = "1.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
