[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
QuasiMonteCarlo = {path = "/home/runner/work/QuasiMonteCarlo.jl/QuasiMonteCarlo.jl"}

[compat]
BenchmarkTools = "1.6.3"
Distributions = "0.25.122"
Documenter = "1"
Plots = "1.41.2"
QuasiMonteCarlo = "0.3.3"
StatsBase = "0.34.8"
